apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: start-ingress
  namespace: start
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - start.example.com
      secretName: start-tls
  rules:
    - host: start.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: start-app
                port:
                  number: 80

