apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: start

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml

commonLabels:
  app: start
  managed-by: kustomize
