apiVersion: v1
kind: Service
metadata:
  name: start-postgres
  namespace: start
  labels:
    app: start-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: start-postgres

