apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "start.fullname" . }}-config
  labels:
    {{- include "start.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
  MAIN_DATASOURCE_URL: {{ .Values.config.mainDatasourceUrl | quote }}
  MAIN_DATASOURCE_USERNAME: {{ .Values.config.mainDatasourceUsername | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: {{ .Values.config.managementEndpointsWebExposureInclude | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: {{ .Values.config.managementEndpointHealthShowDetails | quote }}
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: {{ .Values.config.managementMetricsExportPrometheusEnabled | quote }}
  MANAGEMENT_OTLP_LOGGING_ENDPOINT: {{ .Values.config.managementOtlpLoggingEndpoint | quote }}
  LOGGING_LEVEL_ROOT: {{ .Values.config.loggingLevelRoot | quote }}
  LOGGING_LEVEL_COM_DIGTP_START: {{ .Values.config.loggingLevelComDigtpStart | quote }}

