apiVersion: v1
kind: Secret
metadata:
  name: {{ include "start.fullname" . }}-secret
  labels:
    {{- include "start.labels" . | nindent 4 }}
type: Opaque
stringData:
  MAIN_DATASOURCE_PASSWORD: {{ .Values.secrets.mainDatasourcePassword | quote }}

