apiVersion: v1
kind: Service
metadata:
  name: { { include "start.fullname" . } }
  labels: { { - include "start.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
      protocol: TCP
      name: http
  selector: { { - include "start.selectorLabels" . | nindent 4 } }
